import { generateResourceFromSchema } from './generateFromSchema.js'
import { buildInstanceNames, resolveEdgeBindings } from './edgeResolver.js'
import { buildResourceContext, dedupeInputs } from './terraformBindings.js'
import { moduleGroupsFromNodes, VM_TYPES } from './terraformGroups.js'
import {
  renderModuleOutputs,
  renderProvidersFile,
  renderRootMain,
  renderRootOutputs,
  renderVariables
} from './terraformRenderers.js'
import {
  addFallbackNicInputs,
  renderFallbackNicForVm,
  vmContextBindings
} from './vmTerraformAdapter.js'

function indexNodesById(nodes) {
  return nodes.reduce((acc, node) => {
    acc[node.id] = node
    return acc
  }, {})
}

function buildGroupedModule(group, edges, nodesById, instanceNames) {
  const resourceBlocks = []
  const inputs = []

  for (const node of group.nodes) {
    const bindings = resolveEdgeBindings(node, edges, nodesById, instanceNames)
    const hasExplicitNic = bindings.some((binding) => binding.field === 'network_interface_ids')
    const isVm = VM_TYPES.has(node.data.resourceType)
    const context = buildResourceContext(
      node,
      isVm ? vmContextBindings(bindings, hasExplicitNic) : bindings,
      nodesById,
      instanceNames
    )

    inputs.push(...context.externalInputs)

    const instance = instanceNames[node.id]
    if (isVm && !hasExplicitNic) {
      addFallbackNicInputs(inputs, instance, bindings, nodesById, instanceNames)
      context.properties.network_interface_ids = { __ref: `azurerm_network_interface.${instance}_nic.id` }
      resourceBlocks.push(
        renderFallbackNicForVm(instance, context.properties, bindings, nodesById, instanceNames)
      )
    }

    resourceBlocks.push(
      generateResourceFromSchema(context.schema, instance, context.properties, context.blocks)
    )
  }

  const moduleInputs = dedupeInputs(inputs)
  return {
    name: group.name,
    inputs: moduleInputs,
    files: [
      {
        path: `modules/${group.name}/main.tf`,
        content: `# ${group.label} resources generated by Azure TF Sketchboard\n\n${resourceBlocks.join('\n\n')}\n`
      },
      { path: `modules/${group.name}/variables.tf`, content: renderVariables(moduleInputs) },
      { path: `modules/${group.name}/outputs.tf`, content: renderModuleOutputs(group.nodes, instanceNames) }
    ]
  }
}

export function generateTerraformFiles(nodes, edges) {
  const files = [{ path: 'providers.tf', content: renderProvidersFile() }]

  if (!nodes || nodes.length === 0) {
    files.push({
      path: 'main.tf',
      content: '# No resources defined yet. Drag resources onto the canvas to populate this file.\n'
    })
    return files
  }

  const nodesById = indexNodesById(nodes)
  const instanceNames = buildInstanceNames(nodes)
  const groups = moduleGroupsFromNodes(nodes, instanceNames)
  const modules = groups.map((group) => buildGroupedModule(group, edges, nodesById, instanceNames))

  files.push({ path: 'main.tf', content: renderRootMain(modules) })
  files.push({ path: 'outputs.tf', content: renderRootOutputs(groups, instanceNames) })
  for (const module of modules) files.push(...module.files)

  return files
}

export function generateTerraform(nodes, edges) {
  return generateTerraformFiles(nodes, edges)
    .map((file) => `# === ${file.path} ===\n${file.content}`)
    .join('\n\n')
}
