import { getSchema } from '../schema/schemaUtils.js'
import {
  generateResourceModuleMain,
  generateResourceModuleOutputs,
  generateResourceModuleVariables
} from './generateFromSchema.js'
import { buildInstanceNames, resolveEdgeBindings } from './edgeResolver.js'

const PROVIDERS_TF = `# Generated by Azure TF Sketchboard

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}
`

const padKey = (key, width) => key.padEnd(width, ' ')
const variableNameFor = (fieldPath) => fieldPath.replace(/\./g, '_')

const renderProvidersFile = () => PROVIDERS_TF

// Build the per-instance module dir + the root module-call block for one node.
function buildModuleArtifactsForNode(node, instanceName, bindings) {
  const schema = getSchema(node.data.resourceType)
  if (!schema) {
    throw new Error(`No schema for resource type ${node.data.resourceType}`)
  }

  // Clone properties/blocks and inject {__var: name} placeholders where bindings should live.
  const properties = { ...node.data.properties }
  const blocks = JSON.parse(JSON.stringify(node.data.blocks ?? {}))
  const bindingFields = []
  for (const b of bindings) {
    const variable = variableNameFor(b.field)
    bindingFields.push({ variable, fieldPath: b.field })
    if (b.field.includes('.')) {
      const [parent, child] = b.field.split('.')
      if (!blocks[parent] || typeof blocks[parent] !== 'object') blocks[parent] = {}
      blocks[parent][child] = { __var: variable }
    } else {
      properties[b.field] = { __var: variable }
    }
  }

  const moduleSource = `./modules/${instanceName}`
  const moduleMain = generateResourceModuleMain(schema, properties, blocks)
  const moduleVars = generateResourceModuleVariables(schema, bindingFields)
  const moduleOutputs = generateResourceModuleOutputs(schema)

  const argEntries = bindings.map((b) => [variableNameFor(b.field), b.refExpr])
  const allKeys = ['source', ...argEntries.map(([k]) => k)]
  const keyWidth = Math.max(...allKeys.map((k) => k.length))
  const callLines = [`module "${instanceName}" {`]
  callLines.push(`  ${padKey('source', keyWidth)} = "${moduleSource}"`)
  for (const [argName, argValue] of argEntries) {
    callLines.push(`  ${padKey(argName, keyWidth)} = ${argValue}`)
  }
  callLines.push('}')

  return {
    moduleCall: callLines.join('\n'),
    files: [
      { path: `modules/${instanceName}/main.tf`, content: moduleMain },
      { path: `modules/${instanceName}/variables.tf`, content: moduleVars },
      { path: `modules/${instanceName}/outputs.tf`, content: moduleOutputs }
    ]
  }
}

export function generateTerraformFiles(nodes, edges) {
  const files = [{ path: 'providers.tf', content: renderProvidersFile() }]

  if (!nodes || nodes.length === 0) {
    files.push({
      path: 'main.tf',
      content: '# No resources defined yet. Drag resources onto the canvas to populate this file.\n'
    })
    return files
  }

  const nodesById = nodes.reduce((acc, node) => {
    acc[node.id] = node
    return acc
  }, {})
  const instanceNames = buildInstanceNames(nodes)

  const sorted = [...nodes].sort((a, b) => {
    const aRg = a.data.resourceType === 'azurerm_resource_group'
    const bRg = b.data.resourceType === 'azurerm_resource_group'
    if (aRg && !bRg) return -1
    if (!aRg && bRg) return 1
    if (a.data.resourceType !== b.data.resourceType) {
      return a.data.resourceType.localeCompare(b.data.resourceType)
    }
    return instanceNames[a.id].localeCompare(instanceNames[b.id])
  })

  const moduleCalls = []
  const moduleFiles = []
  for (const node of sorted) {
    const bindings = resolveEdgeBindings(node, edges, nodesById, instanceNames)
    const artifacts = buildModuleArtifactsForNode(node, instanceNames[node.id], bindings)
    moduleCalls.push(artifacts.moduleCall)
    moduleFiles.push(...artifacts.files)
  }

  files.push({
    path: 'main.tf',
    content: `# Generated by Azure TF Sketchboard\n# One module per canvas node — config baked into modules/<name>/.\n\n${moduleCalls.join('\n\n')}\n`
  })
  files.push(...moduleFiles)
  return files
}

export function generateTerraform(nodes, edges) {
  return generateTerraformFiles(nodes, edges)
    .map((file) => `# === ${file.path} ===\n${file.content}`)
    .join('\n\n')
}
