import { getSchema } from '../schema/schemaUtils.js'
import { padKey, outputNameFor } from './terraformNames.js'

export const PROVIDERS_TF = `# Generated by Azure TF Sketchboard

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}
`

export function renderProvidersFile() {
  return PROVIDERS_TF
}

export function renderVariables(inputs) {
  if (inputs.length === 0) return '# No external inputs. This grouped module is self-contained.\n'

  return inputs
    .map((input) => `variable "${input.variable}" {
  description = "Edge-injected value for ${input.fieldPath}"
  type        = ${input.tfType}
}
`)
    .join('\n')
}

export function renderModuleOutputs(nodes, instanceNames) {
  const blocks = []

  for (const node of nodes) {
    const schema = getSchema(node.data.resourceType)
    if (!schema) continue

    const instance = instanceNames[node.id]
    const resourceRef = `${node.data.resourceType}.${instance}`

    for (const attr of ['id', 'name', 'location']) {
      if (!schema.block.attributes?.[attr]) continue
      blocks.push(`output "${outputNameFor(instance, attr)}" {
  description = "${instance} ${attr}"
  value       = ${resourceRef}.${attr}
}
`)
    }
  }

  return blocks.length > 0 ? blocks.join('\n') : '# No outputs generated for this module.\n'
}

export function renderRootMain(modules) {
  const calls = modules.map((module) => {
    const keys = ['source', ...module.inputs.map((input) => input.variable)]
    const width = Math.max(...keys.map((key) => key.length))
    const lines = [`module "${module.name}" {`, `  ${padKey('source', width)} = "./modules/${module.name}"`]

    for (const input of module.inputs) {
      lines.push(`  ${padKey(input.variable, width)} = ${input.refExpr}`)
    }

    lines.push('}')
    return lines.join('\n')
  })

  return `# Generated by Azure TF Sketchboard
# Canvas nodes are grouped into feature modules instead of one module per node.

${calls.join('\n\n')}
`
}

export function renderRootOutputs(groups, instanceNames) {
  const blocks = []

  for (const group of groups) {
    for (const node of group.nodes) {
      const schema = getSchema(node.data.resourceType)
      if (!schema) continue

      const instance = instanceNames[node.id]
      for (const attr of ['id', 'name', 'location']) {
        if (!schema.block.attributes?.[attr]) continue
        const outputName = outputNameFor(instance, attr)
        blocks.push(`output "${outputName}" {
  description = "${instance} ${attr}"
  value       = module.${group.name}.${outputName}
}
`)
      }
    }
  }

  return blocks.length > 0 ? blocks.join('\n') : '# No outputs generated.\n'
}
